# Generated by Django 3.0.5 on 2023-02-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField()),
                ('EDUC', models.IntegerField()),
                ('SES', models.FloatField()),
                ('MMSE', models.FloatField()),
                ('CDR', models.FloatField()),
                ('eTIV', models.IntegerField()),
                ('nWBV', models.FloatField()),
                ('ASF', models.FloatField()),
            ],
        ),
    ]
